### ISSUE TITLE
Contains files with more than one hard link in

### ISSUE THREAD

**Issue by riddertommie** [Luckinber/qbittorrent-manager#1]
I thought i found the holy grail with your script, but I'm keep getting 

`Contains files with more than one hard link in:  /mnt/raid0/.SONARR/blablabla - S02E02`

I'm using docker and i have 

volumes:
      - /mnt/raid0/Torrents/:/downloads

and i have a category 

![image](https://github.com/Luckinber/qbittorrent-manager/assets/3483150/9456d9e0-6000-46ec-b827-c89da4a16de2)

So i changed the config.sh to

```
The path that qBitTorrent thinks your torrents are stored at
RELATIVE_PATH=/downloads

The actual path that your torrents are stored at on your filesystem
ABSOLUTE_PATH=/mnt/raid0/.SONARR
```

But its not working. Do i make a thinking mistake here?
What precisely does Contains files with more than one hard link in main?

Thanks!

**Comment by Luckinber** [comment]
Hi @riddertommie! Thanks for reaching out.

I built this script for a very specific purpose I had in my homelab and I thought why not make it publicly available. I hope it can be useful for you as it is to me!

Regarding your questions, thankyou for pointing them out because I will need to improve my documentation on a few things.

So with your torrents being skipped because they `Contains files with more than one hard link`, this is an intended feature. I made this script to delete torrents that have seeded for long enough AND aren't hardlinked anywhere. I want to keep my hardlinked torrents because they are going to take up the same amount of space so why not seed them. Sonarr and Radarr will create hardlinks if they can, if not they will copy and make a new file.

It's a good point though, I will add the ability to turn the hardlink check off, the other checks as well I guess.

As for the paths, I also need to improve my wording about this. These should be the ROOT directory that qbit is storing stuff, so you said your docker is set up with `- /mnt/raid0/Torrents/:/downloads` then your `config.sh` will be:
```bash
#The path that qBitTorrent thinks your torrents are stored at
RELATIVE_PATH=/downloads

#The actual path that your torrents are stored at on your filesystem
ABSOLUTE_PATH=/mnt/raid0/Torrents
```
I should also make it more clear if it is expecting a trailing /

If you want it to manage Sonarr and Radarr content, make sure to throw their categories in the `config.sh`:
```bash
# The categories of torrents that this script should manage, delimited by spaces eg ("movies" "tv" "books")
MANAGED_CATEGORIES=("SONARRREADY" "RADARRREADY") # I assume
```

Hope this helps and if you find any other issues, please reach out!

**Comment by Luckinber** [comment]
I have fixed/amended the things I commented on, I hope this helps!

You can now set what checks you want to use in `config.sh` and I improved the wording in places where it's not clear.

**Comment by riddertommie** [comment]
Hi @Luckinber thanks for the great explanation and adjusting you script. I did not test i yet, hope to find some time this week. Will let you know. 

Thanks again!

**Comment by Luckinber** [comment]
Best of luck @riddertommie!

**Comment by riddertommie** [comment]
Hi @Luckinber i finally had some time to test and i notice some strange behavior.

First of all the good news, i used  `HARDLINK_CHECK=false` and i seems to work. and iplemented 

> #The path that qBitTorrent thinks your torrents are stored at
> RELATIVE_PATH=/downloads
> 
> #The actual path that your torrents are stored at on your filesystem
> ABSOLUTE_PATH=/mnt/raid0/Torrents

Now the strange things, (I think it's the way i work with SONARR/RADARR, butt i wanted to let you know anyway). The way i use Sonarr is that i first set the category to SONARR and with the help off `Post-Import Category` (this is a SONARR feature) i set the category to SONARRREADY. But if I run the script it also wants to delete file in the SONARR category. 

One extra thing is i use `SEEDING_DAYS_REQUIRED=0` because the explanation of `Post-Import Category` is is de following:

_Category for Sonarr to set after it has imported the download. Sonarr will not remove torrents in that category even if seeding finished. Leave blank to keep same category._ so everything in the SONARRREADY category should be fine te delete.

I will rebuild without the use of `Post-Import Category` and will let you know.

Last question, is i possible to run the script without the question being asked  `Are you sure you want to delete these torrents? [y/N]` if it's find something to delete? something like _dryrun/forced_ so that i can really automate it? 

Hope i'm not over asking ;-) 

Thanks!

**Comment by Luckinber** [comment]
Glad to hear that the checks are working as expected @riddertommie!

And yes, interesting behavior. I never even considered using that Sonarr and Radarr feature, what's the advantage? Seeing as they both just import the torrents when they're done anyway, what's the point of moving categories?

If you want a simple solution you can just remove the normal SONARR and RADARR categories. The script will only manage the categories in the managed categories variable.

I think I would rather suggest that maybe that moving categories functionality is less useful now that this script does the management for you. For me they all just stay in their sonarr/radarr categories and are deleted after 10 days of seeding if they're not being used in a hardlink.

As for the final point, I recently added the ability to just add -y to the and to make it delete without asking. I personally have it running daily using that.

No stress about asking questions! You're making me think about this script outside of my specific use case which helps me improve it.

**Comment by riddertommie** [comment]
@Luckinber 

The reason i used `Post-Import Category` is because i could see at a glance which downloads where ready and not have to search for them. I rebuild without it now and set the seeding day's to 10, all seems to work now! (will know for sure after 10 days of course) but i'm convinced this will go well.

thanks!

**Comment by Luckinber** [comment]
Glad to hear @riddertommie, Enjoy!

And interesting. If you wanted to keep that functionality then you could remove the original categories from the managed variable and add the post import categories. This will leave any of your sonarr/radarr torrents until they are finished and even if they were seeding before they moved categories, the time would be counted as that's gotten directly from the qbit API.

I hope you can tweak it to fit your needs perfectly. If you have any feature requests or issue, feel free to reach out again!

I will mark this as solved for now.
